### ISSUE TITLE
Not correct displayed on small screens

### ISSUE THREAD

**Issue by v1r0x** [nerzhul/owncloud-weather#8]
On my laptop I have a screen size of 1366x768 and this is what it looks like (and I can not scroll down):
![weather](https://cloud.githubusercontent.com/assets/9248714/8763509/d927fae6-2d9f-11e5-941a-b68e395f4878.png)

**Comment by nerzhul** [comment]
Hi, thanks for the report i will add a more responsive design

**Comment by nerzhul** [comment]
b3a2f9bcc2432dcc533b3ff0ff37e4ad67e9be09

**Comment by nerzhul** [comment]
This is now fixed :)

**Comment by v1r0x** [comment]
Unfortunately, it isn't completely fixed. It works for some cities now (e.g. Berlin, from last screenshot works fine), but for other cities it looks similar to the last screenshot.
Maybe this is related to the german translations I use (`lang=DE` in API call). I will look into this and create a PR, if I have some free time (maybe next week).

**Comment by nerzhul** [comment]
Will study it soon, thanks for the report.
Can you give me an example of city which doesn't work ?

**Comment by v1r0x** [comment]
Berlin still doesn't work, another city was ok.
Here a new screenshot of berlin:
![berlin](https://cloud.githubusercontent.com/assets/9248714/8848727/00275658-313a-11e5-8397-3b2efed3198d.png)

**Comment by nerzhul** [comment]
It's now fixed.
