### ISSUE TITLE
Add city: List does not update on add - Enhancement

### ISSUE THREAD

**Issue by Amgine0** [nerzhul/owncloud-weather#9]
Server

    ownCloud version: 8.1.1
    PHP version: 5.4
    HTTPd server: Apache2
    HTTPS: Yes?

Content of /owncloud/data/owncloud.log

Does not generate a log entry.

Description of the issue:

On a clean, git install of the app, adding a city results in error text "Failed to add city. Contact your administrator." However, a page reload will show the city has been added to the list of cities.

Expected behavior:

Once a city is entered, and is found at openweather, the menu list should reload - clearly displaying the addition of the new city.

**Comment by nerzhul** [comment]
@Amgine0 can you tell me which city is this ?

**Comment by Amgine0** [comment]
Any city. This is a duplicate of bug #1, plus an enhancement request that when a city is successfully added the list of cities is reloaded.

**Comment by nerzhul** [comment]
@Amgine0 this is very strange. Have you got some PHP skills to debug why the server do this ? I cannot reproduce this bug :s

**Comment by Amgine0** [comment]
Maybe. I will try to look at it this weekend.

**Comment by nerzhul** [comment]
Thanks

**Comment by nerzhul** [comment]
Can you tell me if e863dd3dba6d0796e9cd482eaa21172cff319559 fixes the problem (don't forget to add an openweathermap api key)

**Comment by MrEnderkiller** [comment]
@nerzhul I have the same problem 
ownCloud version: 8.2.1
PHP version: 5.6
HTTPd server: Apache2
HTTPS: Yes
Weather version 1.3.0 
Seems like the app has been updated to integrate the changes you suggested, but this doesn't fix the problem. It's not a huge inconvenience, but the app is about weather so it would be good to get this fixed. I can help you get some log, but don't have a big PHP knowledge though.

**Comment by nerzhul** [comment]
hi @MrEnderkiller thanks for you report.
Can you look two things: your apache/PHP error logs & your browser JS logs ?

Thanks

**Comment by MrEnderkiller** [comment]
Hi, thanks for your answer.
Upon checking in my Apache log I found this error message (repeated twice) : 

`[Fri Nov 20 11:19:30.665463 2015] [autoindex:error] [pid 11525] [client xx.xx.xx.xx:47951] AH01276: Cannot serve directory /var/www/owncloud/apps/weather/img/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`

Now I don't know much more about this error, I still have somewhat limited knowledge, what I know is that my Directory Includes both index.php and index.html. Do you know what might cause this problem ?

Thanks for all your work.

**Comment by nerzhul** [comment]
@MrEnderkiller sorry but this issue is only a thing to fix for background, not a problem with list reload.
Can you do the following thing:
Go to the app, verify that you have an openweathermap API key setted in the app settings, open your browser developper console in the network tab, add a city, tell me the output of the tab.

**Comment by MrEnderkiller** [comment]
Yes, I have an openweathermap API key set.
Tried what you suggested, here's what I get : 
`POST https://xxx.com/index.php/apps/weather/city/add 404 (Not Found)`
and, in front of that, : 
`angular.min.js?v=3b906e9bffa2976e4c1ff0938a761722`

**Comment by nerzhul** [comment]
@MrEnderkiller strange, i will look at the process. Which city did you added ?

**Comment by MrEnderkiller** [comment]
@nerzhul I tried many of them, such as Paris, New York, Washington DC...
They work after reloading the webpage though.

**Comment by nerzhul** [comment]
thanks @MrEnderkiller i will look at this soon, maybe there is an API problem to check the city before adding it since the new openweathermap API key usage

**Comment by nerzhul** [comment]
@MrEnderkiller i have added some patches this morning, can you test with the commits added to master this morning ? I fixed a problem with city with spaces and unified the HTTP fetching method

**Comment by MrEnderkiller** [comment]
@nerzhul I have trued with these commits, the 404 not found error doesn't appear anymore in the JS console (getting a 200 OK status) but the error message still appears until I relad the page. I tried both cities with spaces and cities without them. This is quite strange as there isn't even a console error anymore, so nowhere to start from to debug it.
I looked again in the Apache / PHP log, nothing new either.

**Comment by nerzhul** [comment]
@MrEnderkiller can you tell me what is the HTTP output on the city/add call in the network tab of browser debugging console please

**Comment by MrEnderkiller** [comment]
Well I don't really know what that corresponds to, what I see in the network tab is, in the "name" column, `add` (which is the line that interests us), the next column called "Status" is `200` (OK), then "type" `xhr` and the initiator column with a few other ones about size and time which aren't of any interest I guess.

**Comment by nerzhul** [comment]
Look at this picture on firefox to find what i need :)
![capture d ecran de 2015-11-21 15-31-00](https://cloud.githubusercontent.com/assets/119752/11318897/e68cacea-9064-11e5-8e99-de48bb685636.png)

**Comment by MrEnderkiller** [comment]
Alright, found it. Strangely, in the response tab I don't have anything, I have written JSON like you but no "id" or anything like that (I have previously selected the "add" POST request). I have checked for other requests and there is response for these, so apparently the client is getting no response for this kind of request I guess. Now I can't interpret that behaviour, if it might be normal or not.
![weather_owncloud_response](https://cloud.githubusercontent.com/assets/15931090/11319003/53750a3e-9068-11e5-90f0-89b4dd12483f.png)

**Comment by nerzhul** [comment]
Okay, what is your DB backend ?

**Comment by MrEnderkiller** [comment]
I'm using MySQL version 5.5.46.

**Comment by nerzhul** [comment]
@MrEnderkiller i changed a little request which is the problematic request for your case, can you pull the last master and retry ? thanks

**Comment by MrEnderkiller** [comment]
@nerzhul Awesome, this worked! No more error message.
Thanks for your help and your commitment into all this stuff. I wish I could do the same as you're doing, but I don't have the knowledge nor the time for this.

**Comment by nerzhul** [comment]
@MrEnderkiller no problem (PS: i'm french too). Thanks for your help and time to help me to reproduce this problem with MySQL. I'm using PgSQL on my test servers and i didn't thought the bug could be due to MAX not indexed as MAX in MySQL with PDO, like PgSQL.
Application is not very difficult to understand if you look at the code it's a tiny code with a angular JS frontend, without too many code you should understand OC & Angular JS easily with this app :)
